### ISSUE TITLE
Fallback host

### ISSUE THREAD

**Issue by mdrost** [php-api-clients/transport#10]
I am writing client for api which have default host url and fallback host url. I am not sure how to achieve fallback behaviour. Should I write my own middleware or somewhere inject [consecutive ConnectionManager](https://github.com/clue/php-connection-manager-extra/blob/master/src/Multiple/ConnectionManagerConsecutive.php)?

**Comment by WyriHaximus** [comment]
On what level should it fallback? In case the low level connection fails or when there was an HTTP level error?

**Comment by mdrost** [comment]
In my case when returned HTTP status code is not 200. But worth considering are all options.

**Comment by WyriHaximus** [comment]
Have you considered creating a service that wraps [`RequestService`](https://github.com/php-api-clients/transport/blob/master/src/Service/RequestService.php) and fallbacks on failure? Out of interest, what happens if the fallback returns a non-200 status code?

**Comment by mdrost** [comment]
I will look into wrapping `RequestService` in the future.
Well, when both servers are inaccessible then user is out of luck and he will get exception. :P

**Comment by WyriHaximus** [comment]
Any luck implementing that feature for your client?

**Comment by mdrost** [comment]
Currently development of my client is stopped - so no.

**Comment by WyriHaximus** [comment]
Ah ok, any reason why you stopped?

**Comment by mdrost** [comment]
1) I realized that my client need PHP 5.6 support
2) Your packages was not stable (and I had no time to help you stabilize them)
But don't worry, I'll be back in the future to this project when I convince someone that he needs async client :P

**Comment by WyriHaximus** [comment]
> I realized that my client need PHP 5.6 support

One of the initial reasons to go 7.0 was to experiment with it's features, and with 5.6 not receiving support for much longer at the time it made perfect sense know the project would take time :smile: .

 > Your packages was not stable

They're pretty stable tbh, just need to tag them. So I'm working on tagging transport somewhere next week and work on from there. Also cleaning up a lot dependencies and simplifying the code. Once all packages have been tagged I'll continue working on the installers that should make bootstrapping new middlewares and clients fairly easy
